import { NextPage } from 'next';
import Head from 'next/head';

import styles from './styles.module.scss';
import { HomeViewPropsInterface } from './view-props.interface';

const HomeView: NextPage<HomeViewPropsInterface> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <h1 className={styles.title}>
        Welcome to <a href='https://nextjs.org'>Next.js!</a>
      </h1>
    </>
  );
};

export default HomeView;
