import { NextPage } from 'next';
import Head from 'next/head';

import styles from './styles.module.scss';

const HomeView: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta content='Generated by create next app' name='description' />
    </Head>
    <h1 className={styles.title}>
      Welcome to <a href='https://nextjs.org'>Next.js!</a>
    </h1>
  </>
);

export default HomeView;
